[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****
=== Technical Constraints

|===
| Constraint | Motivation
| TypeScript | Is the language that will be used in the project
| React | Is the library that help us to make the GUI
| SOLID | Help us to follow a descentralized management of the user data
| POD | Stores the user data and restricts its use unless the user wants to share it
|===

=== Organizational Constraints



=== Conventions

|===
| Constraint | Details
| Language | The language used for the entire documentation and project will be english
| Documentation | The documentation is going to follow the arc42 structure
| Control Version| The developement of the application will be controled by git version control on the platform GitHub
|===