[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== Technology Decisions
==== Back-end

* **Solid:** Gives the user the choice of the data that he wants to share with the application
* **MVC:** The arquitecture that we will be using for the project structure
* **MongoDB:** The type of data base that we will be using for the application
* **MongoDB Atlas:** Is where the data base will be deployed
* **Docker:** Will be used for the deployment of the application
* **Heroku:** Will be used for the deployment of the application

==== Front-end

* **React:** It's a JavaScript library used for doing interfaces. It's based on components.
* **MUI library:** It's a react user interface library that help us on the front-end. 

=== Quality objectives

|===
|**Quality objectives**| **How to obtain them**
|**Privacy**| We are going to store the location of the users to calculate the shipping cost and also the client credit card´s information to carry out the payment of the order
|**Usability**| We are going to design easy-to-use user interfaces to help nobel and experimented users
|**Testability**| We are going to do some tests, both frontend and backend, to guarantee the correct and succesfully functioning of the application
|**Performance**| We are going to use technologies that helps the application performance
|===

=== Development tools

While we develop the proyect we will use the following tools:

* **GitHub:** This platform will help to follow a control of the different versions implemented by each member of the team. We can check as well the work pushed by other members using the pull request to master, to make sure that there are no errors.
* **Visual Studio Code:** We will use this as our source code editor as it has some plugins available to download that will help us in our work of develop this proyect.
* **GitKraken:** This app allows us to change between the different branches easily and shows the commits done in each branches by the members.
* **Docker:** This app makes containers that allows our proyect to be deployed in any machine with Docker installed.

=== Organization

We will use different medias to get in touch and discuss decitions. We have choosen the following ones:

* **WhatsApp:** We can set up a meeting whith messages by this media.
* **Discord:** Will let us to make weekly meetings.
* **Issues:** Used to record the work that each memeber has to do.
* **Wikis:** Used to record the decitions made in each meeting by the members.

==== How we work

We will divide the team into three groups:

* 2 members dedicated to the front-end area
* 2 members dedicated to the back-end area
* 1 member dedicated to SOLID and PODs

Regarding the contributions, front-end and back-end work at the same time and together, therefore, even if the commits are from one, the work has been carried out by the two members.

Lastly, pull requests are accepted by the person who does not commit. Only in the case of the person dedicated to PODs is it reviewed. In the other cases, since it is carried out by two people simultaneously, it is not necessary