[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== 4.1 Back-end



=== 4.2 Front-end

* **React:** it's a JavaScript library used for doing interfaces. It's based on components.
* **Bootstrap Studio:** it's an app for designing and prototyping websites. 

=== 4.3 Quality objectives



=== 4.4 Development tools

While we develop the proyect we will use the following tools:

* **GitHub:** this platform will help to follow a control of the different versions implemented by each member of the team. We can check as well the work pushed by other members using the pull request to master, to make sure that there are no errors.
* **Visual Studio Code:** we will use this as our source code editor as it has some plugins available to download that will help us in our work of develop this proyect.
* **GitKraken:** this app allows us to change between the different branches easily and shows the commits done in each branches by the members.
* **Docker:** this app makes containers that allows our proyect to be deployed in any machine with Docker installed.

=== 4.5 Organization

We will use different medias to get in touch and discuss decitions. We have choosen the following ones:

* **WhatsApp:** we can set up a meeting whith messages by this media.
* **Discord:** will let us to make weekly meetings.
* **Issues:** used to record the work that each memeber has to do.
* **Wikis:** used to record the decitions made in each meeting by the members.