[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Login

1. User will choose Login in the home page.
2. The user will be redirect to the Login page, where he has to fill the gaps with his information.
3. These information will be sent to the Pod.
4. The Pod will accept or not the data provided.
5. If the data is right the user will be redirect to the home page.
6. If the data is wrong the user will be sent again to the Login page.

[plantuml,"Sequence diagram",png]
----
actor User
participant "Home"
participant "Login"
database Pod
User --> "Home": Login
"Home" --> "Login": insertar datos
"Login" --> Pod : validar datos
Pod --> "Login": datos incorrectos
Pod --> "Home": datos correctos
----
