[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

The runtime view describes the possible interactions of the different actors with the application.

This will help us understand how the elements of the application interact at runtime.
The next schemes are some scenarios of our sport online shop.

=== Login

1. Client will choose Login in the home page.
2. The client will be redirect to the Login page, where he has to fill the gaps with his information.
3. This information will be sent to the Pod.
4. The Pod will accept or not the data provided.
5. If the data is right the client will be redirect to the home page.
6. If the data is wrong the client will be sent again to the Login page.

[plantuml,"Sequence diagram",png]
----
actor Client
participant "Home"
participant "Login"
database Pod
Client --> "Home": Login
"Home" --> "Login": insert data
"Login" --> Pod : validate data
Pod --> "Login": wrong data
Pod --> "Home": right data
----


=== Sign up

1. Client will choose Sign up in the home page.
2. The client will be redirect to the Sign up page, where he has to fill the gaps with his information.
3. This information will be sent to the DataBase.
4. If the data of the client is already in the data base, the client will be redirect to the Sign up page.
5. If there isn't any client with the same data in the data base, it will be added and the client will be redirect to the home page.

[plantuml,"Sequence diagram",png]
----
actor Client
participant "Home"
participant "Sign up"
database DataBase
Client --> "Home": Sign up
"Home" --> "Sign up": insert data
"Sign up" --> DataBase : validate data in DB
DataBase --> "Sign up": client exists
DataBase --> DataBase: add client
DataBase --> "Home": right data, client added
----


=== Get the content of the shopping cart

1. Client will login in the application.
2. The client will try to see the content of his shopping cart.
3. The application is going to ask the database for that information.
4. The database will return the list of products.
5. Finally, the application will show the list to the client.

[plantuml,"Sequence diagram",png]
----
actor Client
participant "DeDeportes"
database Database
--> Client: login
Client --> "DeDeportes": access to his shopping cart
"DeDeportes" --> "Database": request the content of the shopping cart
"Database" --> DeDeportes: returns the list of products
"DeDeportes"--> Client: show the cart content
----