[[section-design-decisions]]
== Design Decisions

=== Using a nonSQL database for saving data.
.Problem
Using normal SQL database like HSQLDB for this project is a good choice considering that we have knowledge and practice with this tipe, but in the face of pure documentation and examples MongoDb its a better alternative that fits in this project usisg a MERN frame. 

.Decision
Use MERN as teh project structure. MongoDB used as the project database.

.Status
Accepted

=== Using POD
.Problem
In the project, the application needs to access the client information so it would be a good option to use SOLID to satisfy that need.

.Decision
We will use the user´s PODs. The client will give access to the application and then the app will access the client information.

.Status
Accepted

=== Using a local database at the beginning and then insert it into the project
.Problem
Having the database included in the project from the beginning will make it difficult for us to develop it.

.Decision
To simplify the beginning of the project we will use a local database at the start.
When the project progresses, after the second project´s review we will use Mongo Atlas to deploy the database in the cloud.

.Status
Accepted

=== Choosing the language we´ll use in the documentation
.Problem
Another design decission is the language used in the project. To develop the documentation we have two options, we can write it in English or in Spanish.

.Decision
We have decided to carry out the documentation in English since in this way more people will be able to take charge of the project in a hypothetical future and understand what the project is about.

.Status
Accepted

=== Choosing the storage of images for the webapp
.Problem
Saving the stock images localy can be a problem if the cuantity and size of them are big, also the way to store it online is easier than locally

.Decision
We'll use Cloudiary to store the images, we will save on the database the url pointing to the concrete photo to display it on the webapp.


.Status
Accepted


=== Using an extra database for the tests
.Problem
We have to run the backend tests lots of times to test them, so our database will have lots of unused data.

.Decision
We will use an extra database to run the restapi tests to not fill up our main database since to run the backend tests we need to run them many times.

.Status
Accepted

=== Calculate the distance between two points
.Problem
To calculate the shipping price we need to get the coordinates of the address of the client.

.Decision
We use the MAPBOX api to get the coordinates of the address then with an mathematical formula to calculate the distance, then we asing a cost to the distance.

.Status
Accepted

=== Deployment service
.Problem
To deploy the app we need a provider, we ha thought to use Heroku but at that moment it had a problem.

.Decision
We use AWS to deploy the app, also we deploy it by SSH on the CI.

.Status
Accepted
